#!/bin/bash

source ./cybrtest.config

export CURL="curl -s"
export BASE_URL=http://localhost:8080/cybr
export DEBUG=true

main() {
  # Login as admin to PAS
  PASauthnCreds=$(echo "$PAS_ADMIN_NAME:$PAS_ADMIN_PASSWORD" | base64)
  pasAuthnResponse=$($CURL -H "Authorization: Basic $PASauthnCreds" -H "Content-Type: application/json" "$BASE_URL/pas/login")
  test "paslogin" "$pasAuthnResponse"

  appDbResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/appgovdb?filter=unapproved")
  test "unapproved" "$appDbResponse"
  appDbResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/appgovdb?filter=unprovisioned")
  test "unprovisioned" "$appDbResponse"
  appDbResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/appgovdb?filter=provisioned")
  test "provisioned" "$appDbResponse"
  appDbResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/appgovdb?filter=revoked")
  test "revoked" "$appDbResponse"
  appDbResponse=$($CURL -H "Content-Type: application/json" "$BASE_URL/appgovdb?filter=rejected")
  test "rejected" "$appDbResponse"

}

###################################
test() {
  if ! $DEBUG; then return; fi
  local funcname=$1; shift
  local value="$(echo $1 | tr -d '\r\n')"; shift

  if [[ $value == null ]]; then
    echo "$funcname returned null."
  else
    echo "$funcname returned:"
    echo "$value" | jq .
    echo
  fi
}

main "$@"
