#!/bin/bash

source ./cybrtest.config

export CURL="curl -s"
export BASE_URL=http://localhost:8080/cybr
export DEBUG=true

main() {
  # Login as admin to PAS
  PASauthnCreds=$(echo "$PAS_ADMIN_NAME:$PAS_ADMIN_PASSWORD" | base64)
  pasAuthnResponse=$($CURL -H "Authorization: Basic $PASauthnCreds" -H "Content-Type: application/json" "$BASE_URL/pas/login")
  test "paslogin" "$pasAuthnResponse"

  # Login as admin to Conjur
  ConjurAuthnCreds=$(echo "$CONJUR_ADMIN_NAME:$CONJUR_ADMIN_PASSWORD" | base64)
  conjurAuthnResponse=$($CURL -H "Authorization: Basic $ConjurAuthnCreds" -H "Content-Type: application/json" "$BASE_URL/conjur/login")
  test "conjurlogin" "$conjurAuthnResponse"

  # Add a safe w/ Conjur synch policy
  safeAdd=$($CURL -X POST --url "$BASE_URL/pas/safes?safeName=$PAS_SAFE_NAME&cpmName=$PAS_CPM_NAME&lobName=$PAS_LOB_NAME&vaultName=$PAS_VAULT_NAME")
  test "safeAdd" "$safeAdd"

  # Add an account to the safe & Conjur synchronizer policy
  accountAdd=$($CURL -X POST --url "$BASE_URL/pas/accounts?safeName=$PAS_SAFE_NAME&accountName=$PAS_ACCOUNT_NAME&platformId=$PAS_PLATFORM_ID&address=$PAS_ACCOUNT_ADDRESS&userName=$PAS_ACCOUNT_USERNAME&secretType=$PAS_ACCOUNT_SECRET_TYPE&secretValue=$PAS_ACCOUNT_SECRET_VALUE");
  test "accountAdd" "$accountAdd"

  # Create Conjur base policy for project
  authnResponse=$($CURL --request POST --url "$BASE_URL/conjur/basepolicy?projectName=$PROJECT_NAME&adminName=$PROJECT_ADMIN")
  test "basePolicy" "$authnResponse"

  # Create Conjur safe consumer group under project's base policy
  authnResponse=$($CURL --request POST --url "$BASE_URL/conjur/safepolicy?projectName=$PROJECT_NAME&vaultName=$PAS_VAULT_NAME&lobName=$PAS_LOB_NAME&safeName=$PAS_SAFE_NAME")
  test "safePolicy" "$authnResponse"

  # Create Conjur identity under project's base policy
  authnResponse=$($CURL --request POST --url "$BASE_URL/conjur/identitypolicy?projectName=$PROJECT_NAME&identityName=$CONJUR_IDENTITY")
  test "identityPolicy" "$authnResponse"

  # Grant safe policy role to identity 
  authnResponse=$($CURL --request POST --url "$BASE_URL/conjur/accesspolicy?projectName=$PROJECT_NAME&identityName=$CONJUR_IDENTITY&groupRoleName=$CONJUR_GROUP_ROLE")
  test "accessgrant" "$authnResponse"
}

###################################
test() {
  if ! $DEBUG; then return; fi
  local funcname=$1; shift
  local value="$(echo $1 | tr -d '\r\n')"; shift

  if [[ $value == null ]]; then
    echo "$funcname returned null."
  else
    echo "$funcname returned:"
    echo "$value"
    echo
  fi
}

main "$@"
