#!/bin/bash

source ./cybrtest.config

export CURL="curl -v"
export BASE_URL=http://localhost:8080/cybr
export DEBUG=true

main() {
  # Login as admin to PAS
  PASauthnCreds=$(echo "$PAS_ADMIN_NAME:$PAS_ADMIN_PASSWORD" | base64)
  pasAuthnResponse=$($CURL -H "Authorization: Basic $PASauthnCreds" -H "Content-Type: application/json" "$BASE_URL/pas/login")
  test "paslogin" "$pasAuthnResponse"

  jsonTest="{\"projectName\":\"$PROJECT_NAME\",\"requestor\":\"jhunt\", \"approved\": 1, \"environment\":\"dev\", \"pasVaultName\":\"$PAS_VAULT_NAME\", \"pasSafeName\":\"$PAS_SAFE_NAME\", \"pasCpmName\":\"$PAS_CPM_NAME\", \"pasLobName\":\"$PAS_LOB_NAME\", \"appIdName\":\"$CONJUR_IDENTITY\", \"appAuthnMethod\":\"authn-k8s\"}"

#  appDbResponse=$(
set -x
$CURL -H "Content-Type: application/json" --data "$jsonTest" "$BASE_URL/appgovdb"
#)
#  test "appDbUpdate" "$appDbResponse"

}

###################################
test() {
  if ! $DEBUG; then return; fi
  local funcname=$1; shift
  local value="$(echo $1 | tr -d '\r\n')"; shift

  if [[ $value == null ]]; then
    echo "$funcname returned null."
  else
    echo "$funcname returned:"
    echo "$value"
    echo
  fi
}

main "$@"
